export const PIXOTOPE_PORT = 16208;
export const PIXOTOPE_GATEWAY_BASE_URL = `http://localhost:${PIXOTOPE_PORT}`;
export const PIXOTOPE_GATEWAY_VERSION = "2.2.0";
export const PIXOTOPE_GATEWAY_URL = `${PIXOTOPE_GATEWAY_BASE_URL}/${PIXOTOPE_GATEWAY_VERSION}`;
