export const PIXOTOPE_PORT = 16208;
export const PIXOTOPE_GATEWAY_BASE_URL = `http://127.0.0.1:${PIXOTOPE_PORT}`;
export const PIXOTOPE_GATEWAY_VERSION = "2.2.0";
export const PIXOTOPE_GATEWAY_URL = `${PIXOTOPE_GATEWAY_BASE_URL}/gateway/${PIXOTOPE_GATEWAY_VERSION}`;
